### ISSUE TITLE
Any good alternative for sitemap generation?

### ISSUE THREAD

**Issue by p1ho** [p1ho/site-validator-cli#2]
I need a sitemap generation tool that keeps the sitemap in memory instead of writing directly to disk. **[sitemap-generator](https://www.npmjs.com/package/sitemap-generator)** writes directly to disk, and this can be costly if this is run on a drive where read/write cycles are precious, such as SSDs.

I initially tried using **[sitemap-crawler](https://www.npmjs.com/package/sitemap-crawler)**, but this doesn't actually get the complete sitemap. If there are links not accessible through the url given (but is accessible from a link from the url), it will not get returned.

Any recommendations?

**Comment by zrrrzzt** [comment]
Take a look at [simplecrawler](https://www.npmjs.com/package/simplecrawler). This was the crawler used for `w3c-validator-cli`

**Comment by p1ho** [comment]
Will test it out soon, thanks!

**Comment by p1ho** [comment]
#7

**Comment by p1ho** [comment]
#7 Included **[simplecrawler](https://www.npmjs.com/package/simplecrawler)** in a new PR

**Comment by p1ho** [comment]
PR merged. Closing.
