### ISSUE TITLE
Checklist before publishing

### ISSUE THREAD

**Issue by p1ho** [p1ho/site-validator-cli#22]
I think we've hit all the major functionalities.
Aside from tests, I'm actually not sure if there's anything additional I need to do.
If it's not too much trouble, could you please start a checklist? Thanks!

**Comment by zrrrzzt** [comment]
- [x] Tests
- [x] Check descriptions
- [x] Check README
- [x] Some sort of CI/CD (GitHub actions might be enough)
- [x] Release

The CI/CD is probably more nice to have than need to have.

I guess you could release it without any of this and still deliver value for users but I'm all in for doing it proper :-)

Edit: Turned list into checklist

**Comment by p1ho** [comment]
Cool, I'll work on these tonight and create a PR.

**Comment by zrrrzzt** [comment]
Looks like GitHub actions are in Beta. Don't know if you have it available for your repos.
I've use [Travis](https://travis-ci.com/) as my go to CI but it seems like the future of the service is uncertain. Anyway this is my typical .travis.yml

```
language: node_js
node_js:
  - "8"
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  on:
    tags: true
    branch: master
```

This will deploy my module to npm if tests pass for every tagged release I do to GitHub

`$NPM_EMAIL` and `$NPM_TOKEN` are environment variables in Travis.

If you have access til GitHub Actions, this is the workflow I use for npm modules

```
workflow "Build, Test, and Publish on release" {
  resolves = ["Publish"]
  on = "release"
}

action "Build" {
  uses = "actions/npm@master"
  args = "install"
}

action "Test" {
  needs = "Build"
  uses = "actions/npm@master"
  args = "test"
}

action "Publish" {
  needs = "Test"
  uses = "actions/npm@master"
  args = "publish --access public"
  secrets = ["NPM_AUTH_TOKEN"]
}
```

**Comment by p1ho** [comment]
I've signed up for the beta, but I don't have access yet.
I can try to figure out CI/CD later, I will focus on writing tests tonight.

Realistically, I think I'll only write tests for the ```get-urls``` modules.
The validation part is essentially pretty-printing results from ```html-validator``` and we know that works.

**Comment by zrrrzzt** [comment]
Agreed. Parts of the validation code like `isNotFound`, `isValidHtml` and `failFast` could be refactored into modules with unit tests. You can always do that later.

`print-error.js` should have tests though.

**Comment by p1ho** [comment]
This is probably trivial, but I was wondering if it would be a good idea if we create a mini test_site with just a few webpages in this repository under `./test/data`
the pages could then be passed to w3c validator with path `https://p1ho.github.io/site-validator-cli/test/data/...`
I think this reduces the dependency of our tests on `https://alheimsins.net/` being alive

**Comment by zrrrzzt** [comment]
Yup. Better to have full control of pages for testing :-)

**Comment by p1ho** [comment]
OK! I will start refactoring the tests. Will submit after the latest one is merged.

**Comment by p1ho** [comment]
Addressed in #40

**Comment by p1ho** [comment]
@zrrrzzt 
I've set up the `.travis.yml`, I wonder if this is ready to be published, or that there are other CI/CD steps I'd have to do?

Edit: I'm looking at [coveralls.io](https://coveralls.io/), the coverall number will probably not be great but I think it's ok.

**Comment by p1ho** [comment]
Published on npm at [https://www.npmjs.com/package/site-validator-cli](https://www.npmjs.com/package/site-validator-cli). Closing!
