### ISSUE TITLE
Use console.error for errors

### ISSUE THREAD

**Issue by zrrrzzt** [p1ho/site-validator-cli#32]
Use `console.error` and not `console.log` for all error situations.

Example: https://github.com/p1ho/site-validator-cli/blob/master/lib/helpers-validate-pages/print-error.js#L17 and https://github.com/p1ho/site-validator-cli/blob/master/lib/helpers-validate-pages/print-error.js#L17

**Comment by p1ho** [comment]
Should be fixed in the latest PR #34 
Will close after merge
