### ISSUE TITLE
Reorganize code to make it more flexible

### ISSUE THREAD

**Issue by zrrrzzt** [p1ho/site-validator-cli#4]
I suggest to move the crawler to it's own module and to make the validation part accept an array of urls.

By doing this it will be easy to switch to another crawler and it would be trivial to make the cli support sitemaps or just an array of urls for validation.

**Comment by p1ho** [comment]
Yes, I think that's a good idea.
A sitemap makes it impossible for users to specify just the pages they want to test.
I can definitely modularize the code a little bit, so URL gathering and validation are decoupled more nicely.

Do you have recommendations on how to accept user specified arrays of URLs nicely?
I was thinking of accepting xml / json / txt from a local file with the following format:

**xml**: has to be exact same structure for sitemap so some existing code can be reused

**json**:
```
{ 'urls': [ "https://www.example.com/", "https://www.example.com/about", ... ] }
```
**txt**:
```
https://www.example.com/
https://www.example.com/about
...
```
This means users could now do
```
$ site-validator <path-to-file>
```
Would these work?

**Comment by zrrrzzt** [comment]
I agree regarding xml and txt.

For json I would prefer something like this

```JavaScript
[
  "https://www.example.com",
  "https://www.example.com/about"
]
```

By using some switches you could probably make the api for the module very similar for files and urls

```
$ site-validator <url-or-path-to-file>
```

If input starts with http it's a url else it's a file. You can guess filetype from file ending.
The url can be a sitemap or a base url for crawling.

I have some free time now so if you want me to code something just tell me :-)

**Comment by p1ho** [comment]
Thanks! I will take your suggestion on the json format.

With the switch between files/urls it could be a bit tricky.
I originally intended for url as the only allowed format, which allowed me to use [normalize-url](https://www.npmjs.com/package/normalize-url) for incomplete urls (such as ```example.com```), This means it could be trickier to differentiate between file/url using just the input (Would need a really nice regex).

A somewhat lazy approach is to make users enter a flag like
```
$ site-validator <path-to-file> --file
```
to differentiate.

There was this ["In search of of the perfect URL validation regex"](https://mathiasbynens.be/demo/url-regex) for PHP, but in this one, ```example.com``` would actually fail.

Or, I could just require users to enter the protocol for the input, then your recommendation would work.

**Comment by p1ho** [comment]
It just hit me!

I could just check the ending, if users do not have ```.xml``` ```.json``` ```.txt```, then I assume it's a URL.

**Comment by zrrrzzt** [comment]
You could just use a module like [path-type](https://www.npmjs.com/package/path-type) and if it's not a file it's probably a url

```JavaScript
(async () => {
  const pathType = require('path-type')
  const query = process.argv[2]
  console.log(query)
  const isFile = await pathType.file(query)
  console.log(isFile)
})()
```

**Comment by zrrrzzt** [comment]
`.xml`, `.json`and `.txt` could be valid endings for a url. Especially .xml if you want to support giving sitemap from the site

**Comment by p1ho** [comment]
I think that would work, I'm just confused why anyone would try to validate xml, json, or txt files on a webserver against an HTML validator.

**Comment by zrrrzzt** [comment]
`.xml` could typically be a sitemap
the others not so much :-)

so a lightweight alternative could be to check endings and if it's xml also check start (would be http for a sitemap url)

**Comment by p1ho** [comment]
OK for sure! I think I might implement something like this:
```JavaScript
if input.toLowerCase().endsWith('.xml')

  xml = parseXml(input) // returns object, function handles both local / online file.
  if isSitemap(xml)
    // trim invalid urls
    // validates valid urls
  else
    // throw xml is not formatted like a sitemap error

else if input.toLowerCase().endsWith('.json')

  json = getJson(input) // returns object, function handles both local / online file.
  if jsonPassed(json)  // has to be an array
    // trim invalid urls
    // validates valid urls
  else
    // throw json failed format test error

else if input.toLowerCase().endsWith('.txt')

  // returns array (each item represents 1 line), function handles both local / online file.
  txt = getText(input)

  // trim invalid urls
  // validates valid urls

else
  // assume it's a url, and generate its sitemap through crawling
```

**Comment by zrrrzzt** [comment]
I guess this really is a matter of how you prefer your code. I would probably write something like this

```JavaScript
const normalizeUrl = require('normalize-url');
const urlsFromXml = require('./lib/parse-xml')
const urlsFromJson = require('./lib/parse-json')
const urlsFromTxt = require('./lib/parse-text')
const urlsFromCrawling = require('./lib/urls-from-crawler')
let urls = []

// get an array of urls depending on input
if (input.toLowerCase().endsWith('.xml')) {
  urls = urlsFromXml(input)
} else if (input.toLowerCase().endsWith('.json')) {
  urls = urlsFromJson(input)
} else if (input.toLowerCase().endsWith('.txt')) {
  urls = urlsFromTxt(input)
} else {
  urls = urlsFromCrawling(input)
}

// normalize the urls
let pagesToValidate = urls.map(normalizeUrl)

const validateNextPage = async () => {
  // the function as it is
}

await validateNextPage()
```

By doing this every parse module would be testable and your `index.js` would be very clean and readable.

Every parse module would have to return an array of urls.

**Comment by p1ho** [comment]
I think this is nice!
And I agree this makes testing a lot easier, there is probably no need to write tests for the whole program (like treating it as a giant black box) if it can be modularized with each module easily testable.
I will try to get around to it tomorrow, and I think I will open another issue when I get around to writing tests.

**Comment by p1ho** [comment]
#12

**Comment by p1ho** [comment]
I'm working on a pretty big update that will modularize a lot of existing code, will push soon

**Comment by p1ho** [comment]
#16

**Comment by p1ho** [comment]
I think all the points in this thread have been hit, will close this issue.
