### ISSUE TITLE
lib subfolders not published

### ISSUE THREAD

**Issue by p1ho** [p1ho/site-validator-cli#42]
I may have misconfigured `package.json` because subfolders in `lib` folder was not getting downloaded by npm. I'm trying to debug this at the moment, and I have unpublished it (because it won't work).

**Comment by p1ho** [comment]
I'm hoping [this](https://github.com/p1ho/site-validator-cli/commit/3b3787cda88579625d00db5199869d14ffbd115f) is the issue. 
npm won't let me publish again until 24 hours have passed.

In the meantime, looked at a few things:

1. [this approach](https://medium.com/@the1mills/ready-to-go-publishing-npm-packages-the-right-way-bbb4f0eb4ec2) (Read the [doc](https://www.npmjs.com/package/r2g), doesn't work on MS Windows)

1. `npm uninstall . -g` does not respect `files` in `package.json` so it's not a good choice.

1. Checked out [package-preview](https://github.com/zkochan/package-preview) This seems like a good alternative, it will create a package 1 level above your project's root.

1. Will try `npm-pack` / `npm publish --dry-run`

**Comment by zrrrzzt** [comment]
Ahhh, sorry to hear that. Didn't catch that myself either.

**Comment by p1ho** [comment]
That's alright! Will close after publish tonight.

**Comment by p1ho** [comment]
[Published](https://www.npmjs.com/package/site-validator-cli) and closing
