### ISSUE TITLE
--cacheTime to --cache

### ISSUE THREAD

**Issue by p1ho** [p1ho/site-validator-cli#46]
I think it looks syntactic cleaner (with everything lowercase) if the syntax reads
```
$ site-validator example.com --cache 30
```
instead of the current way
```
$ site-validator example.com --cacheTime 30
```

**Comment by zrrrzzt** [comment]
Agreed.

To avoid a breaking change we could support both until next major release.

**Comment by p1ho** [comment]
Will do!
