### ISSUE TITLE
Cannot add options to command

### ISSUE THREAD

**Issue by rbrv** [p1ho/site-validator-cli#60]
Running the command with any option, like  
`./node_modules/.bin/site-validator --verbose https://google.com`  
returns error  
`TypeError: Cannot read property 'toLowerCase' of undefined`

Running without options works fine, e.g.  
`./node_modules/.bin/site-validator https://google.com`

Sidenote: running the command with an option after the URL, ignores the option, e.g.  
`./node_modules/.bin/site-validator https://google.com --verbose`

### Platform
- OSX
- Node 10.16

**Comment by p1ho** [comment]
Gotcha, thanks for reporting. I intended for the url to be the first argument.

try either one of the 2:
`site-validator --verbose --url https://google.com` or
`site-validator https://google.com --verbose`

When I have time I will fix this so it fails more gracefully with instructions.

**Comment by p1ho** [comment]
Although I would not use google as a testing site for this. Preferrably something with a much smaller sitemap.

**Comment by rbrv** [comment]
Of course, google.com was just an example :)

Your examples work, thanks!  

In the meantime I've stumbled into another issue with localhost. Will create a new issue.

**Comment by p1ho** [comment]
Sounds good!

**Comment by p1ho** [comment]
Just made a quick release. Right now it will fail more gracefully
```bash
$ site-validator --verbose google.com

No path entered.
If path is not the 1st argument, you must prepend it with --url or --path.
```
Thanks for the report. Closing this issue.
