### ISSUE TITLE
Problem validating http://localhost

### ISSUE THREAD

**Issue by rbrv** [p1ho/site-validator-cli#61]
Validating pages on localhost using the command
`./node_modules/.bin/site-validator --url http://localhost --local --verbose`
returns no results:

```
Fetching Site Urls for http://localhost ...
This may take a while...

Pages crawled:
No Urls Found, retrying with HTTP...

Success Site URLs Cache found for http://localhost

Pages found in cache

Error: No Urls found
```

- Browsing to http://localhost works fine
- Example of links on the page: `<a href="http://localhost/about-us">About us</a>`
- Output of cache/sitemap [here](https://github.com/p1ho/site-validator-cli/files/3816976/8523ab8065a69338d5006c34310dc8d2c0179ebb.txt)

### Platform
- OSX
- Node 10.16

**Comment by p1ho** [comment]
In the current version you have to specify the port number, so try
`site-validator localhost:80 --local`

I felt conflicted about making it default to 80 because right now a lot of frameworks will use other port numbers like 3000

Edit: My mistake, if it's on port 80, `localhost` without the port number is ok. However, if the localhost is served on a different port, then it would be needed. I will play around with setting up a HTTPS connection localhost to see if it also defaults to 443 as well. Will update the documentation after testing.

**Comment by rbrv** [comment]
Valid reasoning.

Trying `./node_modules/.bin/site-validator localhost:80 --local --verbose` returns the same result:

```
$ ./node_modules/.bin/site-validator localhost:80 --local --verbose

Fetching Site Urls for http://localhost ...
This may take a while...

Pages crawled:
No Urls Found, retrying with HTTP...

Success Site URLs Cache found for http://localhost

Pages found in cache

Error: No Urls found
```

**Comment by p1ho** [comment]
OK yes, there is some bug going on there. I will take a look later.
In the mean time try this:
`site-validator localhost:80 --local --verbose --clear-cache`

**Comment by rbrv** [comment]
Same result... Thx for your help!

**Comment by p1ho** [comment]
Hm... I am unable to reproduce the issue.
When you enter localhost into your web browser, what do you see?

**Comment by rbrv** [comment]
I see the website and can browse through the pages as normal.

`curl http://localhost` also outputs the html.

**Comment by p1ho** [comment]
Can you please show me the output using my command earlier?
I tried it and the sitemap does get generated.
<img src="https://user-images.githubusercontent.com/22629067/68345902-9e6ebe00-00c0-11ea-9dd4-665460e62bea.png" width="450">

**Comment by rbrv** [comment]
Sure:

<img width="627" alt="Schermafbeelding 2019-11-07 om 00 15 31" src="https://user-images.githubusercontent.com/43676281/68346212-d511fc00-00f3-11ea-9caf-2dff1b076afe.png">

**Comment by p1ho** [comment]
I see... honestly it's hard for me to guess what's going on.
It's likely I screwed up somewhere, but just to make sure, could you please try to crawl `http://localhost` with [simplecrawler](https://www.npmjs.com/package/simplecrawler?activeTab=readme)? This package uses `simplecrawler` so if it fails, we know the problem may be more upstream.

Let me know if you need any help setting it up.

**Comment by rbrv** [comment]
Good idea! Will try this soon. Thx again for the help.

**Comment by rbrv** [comment]
Closing this. Was caused by the framework we're using. 
Some extra debug-javascript output after the <html> tag is closed on localhost was the cause.

Thanks again and keep up the good work!

**Comment by p1ho** [comment]
Awesome!
I actually made a mistake in my earlier comment, you actually don't need the port number if it's served on port 80. I think when I was developing this months ago I may have served mine on a different port that made me think you'd need to specify the port number no matter what.

I will play around with HTTPS connection to see if it also defaults to 443 without specifying. I will also update the documentation accordingly after my testing. Thanks for bringing this to my attention!

Edit:
Just tried setting up a local VHOST that serves through HTTPS on port 443, `simplecrawler` has trouble picking it up, will make a note in the documentation that local HTTPS connection is not currently supported.
