### ISSUE TITLE
Add a linter/code formatter

### ISSUE THREAD

**Issue by zrrrzzt** [p1ho/site-validator-cli#8]
I suggest you add a linter to catch stupid bugs and a code formatter to make sure the codebase looks consistent.

I usually go for [standard](https://www.npmjs.com/package/standard) and if you love your semicolons you could use [semistandard](https://github.com/Flet/semistandard)

**Comment by p1ho** [comment]
I see, I'll go with standard. I could go one way or another because I also use Python.
I've been using semicolons because I deal with PHP a lot more (not an expert though!)

I'll install the standard formatter as a dev-dependency and update the package.json files.

**Comment by zrrrzzt** [comment]
Cool. Used a lot of Python in my previous life. These days almost only JavaScript/Node.

If you add this to scripts in `package.json`

`"standard-fix": "standard --fix"` you will be able to run `$ npm run standard-fix`to fix everything standard can handle for you.

**Comment by p1ho** [comment]
Thank you, I was literally trying to figure out what to put inside the scripts inside package.json.
I'll put this in and commit a formatted version asap, so it doesn't add noise to later work.

**Comment by p1ho** [comment]
I'm trying to debug this, it made change to the code, but there seems to be errors.
![image](https://user-images.githubusercontent.com/22629067/52993576-b2637a00-33e2-11e9-9a62-72b766b585ab.png)

**Comment by p1ho** [comment]
I'm trying to debug this, it made change to the code, but there seems to be errors.

```PowerShell
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! site-validator-cli@1.0.0 standard-fix: `standard --fix`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the site-validator-cli@1.0.0 standard-fix script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ASUS\AppData\Roaming\npm-cache\_logs\2019-02-19T06_04_26_079Z-debug.log
```

Edit: It looks like the codes have all been linted, can I disregard this?

**Comment by zrrrzzt** [comment]
You can of course disregard it but that kind of removes the point of a linter :-)

Usually there are a lot of lines describing errors. Typically unused variables, missing camelCase and so on.

Using snake_case I guess is an old python habit.

**Comment by p1ho** [comment]
Yes, I'm going through each one of those right now, give me 5-10 minutes.
I should use linters more often for my projects.
I usually tend to do:
1. upper camel case for class names
1. lower camel case for methods
1. snake_case for variable names

**Comment by zrrrzzt** [comment]
Super!

My basic dev dependencies for Node are
- standard for linting/formatting
- ava for tests
- nyc for coverage
- coveralls for coveralls :-)

This is my basic script setup

```JavaScript
"scripts": {
    "test": "standard && npm audit && ava",
    "test-offline": "standard && ava"
  }
```

By running `$ npm test` the code is linted, checked for malicious dependencies and tested.
`test-offline`skips `npm audit`

**Comment by p1ho** [comment]
I see, I'm still figuring out the stuff I need to put under "ava" in package.json.
I will commit my changes when ready.

**Comment by p1ho** [comment]
I've committed the changes and running 
```npm run test```
passes.
I've not familiar with nyc and coveralls yet, I will add them once I understand better what they do!

**Comment by zrrrzzt** [comment]
`nyc` and `coveralls` are only necessary if you want/need to have reports for code coverage.
